/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.sopa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adolfo Castillo, Andrea Sanchez, Luciano Rojas 
 */
public class Ventana1 extends javax.swing.JFrame {

    public static Inicio v1;
    
    /**
    * Constructor de la clase Ventana1.
    * Inicializa los componentes gráficos de la ventana y carga la sopa de letras
    * desde el grafo del objeto Inicio pasado como parámetro.
    *
    * Agrega al modelo de la tabla "jTable1" las letras del grafo, organizadas en
    * filas de 4 caracteres, de acuerdo a los vértices del grafo.
    *
    * @param v1 instancia de la clase Inicio que contiene el grafo y las palabras a buscar
    */
    public Ventana1(Inicio v1) {
        initComponents();
        this.v1 = v1;
        
        // Obtener el modelo actual de la tabla
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

//        String[] palabra = v1.palabras;
//        for (int i = 0; i < 16; i += 4) {
//            System.out.println(v1.grafo.vertices[i].getLetras());
//            v1.grafo.vertices[i].getListainterna().Imprimir();
//            
//        }
        for (int i = 0; i < 16; i += 4) {
            // Creamos una fila de 4 letras extraídas de los vértices
            String letra1 = v1.grafo.vertices[i].getLetras();
            String letra2 = v1.grafo.vertices[i + 1].getLetras();
            String letra3 = v1.grafo.vertices[i + 2].getLetras();
            String letra4 = v1.grafo.vertices[i + 3].getLetras();

            model.addRow(new Object[]{letra1, letra2, letra3, letra4});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoBusqueda = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        palabras = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sopa de letras");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jButton1.setText("Busqueda por DFS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButton2.setText("Busqueda por BFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        resultadoBusqueda.setColumns(20);
        resultadoBusqueda.setRows(5);
        jScrollPane1.setViewportView(resultadoBusqueda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 290, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("la sopa de letras mediante los metodos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Se buscaran todas las palabras que posea");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Volver a cargar informacion: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));
        jPanel1.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, -1));

        jButton3.setText("Cargar Informacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        palabras.setColumns(20);
        palabras.setRows(5);
        jScrollPane2.setViewportView(palabras);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, 150));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Indica una palabra específica a ser buscada:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jButton4.setText("Buscar palabra");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 220, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
    * Acción ejecutada al presionar el botón "Busqueda por DFS".
    * Recorre todas las palabras almacenadas en el objeto "Inicio" y verifica
    * si están presentes en el grafo usando búsqueda en profundidad (DFS).
    * 
    * Muestra en el área de texto `palabras` todas las palabras encontradas
    * y el tiempo total de ejecución.
    *
    * @param evt el evento de acción generado por el botón
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Profundidad
        
        this.palabras.setText("");
        long startTime = System.currentTimeMillis();
        
        for (int i = 0; i < v1.palabras.length; i++) {
            String palabra = v1.palabras[i];
            boolean respuesta = v1.grafo.profundidad(palabra);
            if (respuesta) {
                this.palabras.setText(palabras.getText() + "\n" + palabra);
            }
        }
        
        long endTime = System.currentTimeMillis();
        long tiempoDeEjecucion = endTime - startTime;
        
        this.palabras.setText(palabras.getText() + "\n \n" + "Tiempo de ejecución: " + tiempoDeEjecucion + " milisegundos");
        //JOptionPane.showMessageDialog(null, "Tiempo de ejecución: " + tiempoDeEjecucion + " milisegundos");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
    * Acción ejecutada al presionar el botón "Busqueda por BFS".
    * Recorre todas las palabras almacenadas en el objeto "Inicio" y verifica
    * si están presentes en el grafo usando búsqueda en amplitud (BFS).
    * 
    * Muestra en el área de texto "palabras" todas las palabras encontradas
    * y el tiempo total de ejecución.
    *
    * @param evt el evento de acción generado por el botón
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Amplitud
        this.palabras.setText("");
        long startTime = System.currentTimeMillis();
        
        for (int i = 0; i < v1.palabras.length; i++) {
            String palabra = v1.palabras[i];
            boolean respuesta = v1.grafo.amplitud(palabra);
            if (respuesta) {
                this.palabras.setText(palabras.getText() + "\n" + palabra);
            }
        }
        
        long endTime = System.currentTimeMillis();
        long tiempoDeEjecucion = endTime - startTime;
        
        this.palabras.setText(palabras.getText() + "\n \n" + "Tiempo de ejecución: " + tiempoDeEjecucion + " milisegundos");
        //JOptionPane.showMessageDialog(null, "Tiempo de ejecución: " + tiempoDeEjecucion + " milisegundos");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Acción ejecutada al presionar el botón "Buscar palabra".
     * Realiza la búsqueda de una palabra específica (escrita por el usuario)
     * usando el método "recorridoBFSIndices" del grafo.
     * 
     * Si la palabra es encontrada, resalta letra por letra en la tabla "jTable1"
     * con una animación temporal. Si no es encontrada, muestra un mensaje indicando
     * que no se halló la palabra.
     *
     * @param evt el evento de acción generado por el botón
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String palabra = this.buscador.getText().toUpperCase();
        resultadoBusqueda.setText("");

        if (palabra.length() < 3) {
            resultadoBusqueda.setText("La palabra debe tener al menos tres letras");
            return;
        }

        int[] recorrido = v1.grafo.recorridoBFSIndices(palabra);

        if (recorrido.length == 0) {
            resultadoBusqueda.setText("La palabra " + palabra + " no ha sido encontrada");
            return;
        }

        resultadoBusqueda.setText("La palabra " + palabra + " ha sido encontrada");

        Thread animacion = new Thread(() -> {
            for (int i = 0; i < recorrido.length; i++) {
                int idx = recorrido[i];
                int fila = idx / 4;
                int col = idx % 4;

                jTable1.changeSelection(fila, col, false, false);
                jTable1.editCellAt(fila, col);

                // Mostrar letra en rojo y negrita temporalmente
                jTable1.setValueAt("<html><b><font color='red'>" +
                    v1.grafo.vertices[idx].getLetras() + "</font></b></html>", fila, col);

                try {
                    Thread.sleep(600);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }

                // Restaurar la letra original
                jTable1.setValueAt(v1.grafo.vertices[idx].getLetras(), fila, col);
            }
        });

        animacion.start();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
    * Acción ejecutada al presionar el botón "Cargar Información".
    * Crea una nueva instancia de la clase "Inicio", mostrando su ventana
    * y ocultando la actual.
    *
    * @param evt el evento de acción generado por el botón
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Inicio nuevoInicio = new Inicio();
        nuevoInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea palabras;
    private javax.swing.JTextArea resultadoBusqueda;
    // End of variables declaration//GEN-END:variables
}
